services:
  redis:
    image: redis:6.2
    container_name: recruiter-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
        - main-internal-net

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: recruiter-dev-selenium
    ports:
      - "14440:4444"
    environment:
      - SE_NODE_ENABLE_MANAGED_DOWNLOADS=true
      - SE_OPTS=--enable-managed-downloads true
      - SE_LOG_LEVEL=INFO
    restart: always
    shm_size: 4gb
    networks:
        - main-internal-net

  backend:
    build:
      context: ./backend
    container_name: recruiter-dev-backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 7013
    ports:
      - "18000:7013"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - selenium
    environment:
      - REDIS_HOST=recruiter-dev-redis
      - REDIS_PORT=6379
      - REMOTE_DRIVER_URL=recruiter-dev-selenium
    networks:
        - main-internal-net


  frontend:
    build:
      context: ./frontend 
    container_name: recruiter-dev-frontend
    ports:
      - "8080:80"
    networks:
      - main-internal-net
    depends_on:
      - n8n
    volumes:
      - ./frontend:/app  # Montar solo la subcarpeta para desarrollo
      - /app/node_modules

  n8n:
    build:
      context: ./workflows
    container_name: recruiter-dev-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - REDIS_HOST=recruiter-dev-redis
      - REDIS_PORT=6379
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/data
    depends_on:
      - backend
    networks:
        - main-internal-net

volumes:
  redis_data:
  n8n_data:
  
networks:
  main-internal-net:
    driver: bridge
