name: print_ia_chat_bot
description: Chatbot to stay informed about the latest Hacker News and get information about different books
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dash_chat_2: ^0.0.21
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen_ai_chat_ui: ^2.0.8
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_parser: ^4.1.2
  intl: ^0.19.0
  provider: ^6.1.4
  record: ^6.0.0
  waveform_recorder: ^1.7.0

dev_dependencies:
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

dependency_overrides: 

  intl: ^0.20.2
  path: ^1.9.1

flutter:
  uses-material-design: true
  generate: true
